# auto generated by step-0; do not edit

name          = "example123"
cluster_name  = "example123"
region        = "us-east-1"
azs           = ["us-east-1b", "us-east-1f"]
public_domain = "example123.legionx.com"
