provider "aws" {
  region                  = var.region
  shared_credentials_file = "aws_credentials"
}

locals {
  name = "${var.cluster_name}-terraform-state"
}

resource "aws_s3_bucket" "terraform_state" {
  bucket = local.name
  acl    = "private"

  # Enable versioning so we can see the full revision history of our
  # state files
  versioning {
    enabled = true
  }
  # Enable server-side encryption by default
  server_side_encryption_configuration {
    rule {
      apply_server_side_encryption_by_default {
        sse_algorithm = "AES256"
      }
    }
  }

  lifecycle {
    prevent_destroy = true
  }
}

resource "aws_s3_bucket_public_access_block" "terraform_state" {
  bucket = aws_s3_bucket.terraform_state.id

  block_public_acls       = true
  block_public_policy     = true
  ignore_public_acls      = true
  restrict_public_buckets = true
}

resource "aws_dynamodb_table" "terraform_locks" {
  name         = local.name
  billing_mode = "PAY_PER_REQUEST"
  hash_key     = "LockID"
  attribute {
    name = "LockID"
    type = "S"
  }
}

resource "local_file" "step-N-backend" {
  count    = 5
  filename = "${path.module}/../step-${count.index}/backend.tf"
  content  = <<-EOF
    # auto generated by step-0; do not edit

    terraform {
      backend "s3" {
        # key must be different for each step-#
        key = "step-${count.index}/terraform.tfstate"

        # everything below must be same for all steps
        bucket         = "${aws_s3_bucket.terraform_state.bucket}"
        dynamodb_table = "${aws_dynamodb_table.terraform_locks.name}"
        region         = "${var.region}"
        encrypt        = true

        shared_credentials_file = "../step-0/aws_credentials"
      }
    }
    EOF
}

resource "local_file" "step-0-variables" {
  count    = length(local_file.step-N-backend) - 1
  filename = "${path.module}/../step-${count.index + 1}/step-0-variables.tf"
  content  = file("${path.module}/variables.tf")
}

resource "local_file" "step-0-tfvars" {
  count    = length(local_file.step-N-backend) - 1
  filename = "${path.module}/../step-${count.index + 1}/step-0-variables.auto.tfvars"
  content  = <<-EOF
    # auto generated by step-0; do not edit

    cluster_name   = "${var.cluster_name}"
    region = "${var.region}"
    azs    = [${join(", ", formatlist("\"%s\"", var.azs))}]
    public_domain = "${var.cluster_name}.legionx.com"
    EOF
}
